language: 
  - node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_greeting_test

before_script:
  - psql -c 'create database my_greeting_test;' -U postgres
  - psql -U postgres -d my_greeting_test -a -f table.sql

services:
  - postgresql
